

import React, { useEffect, useState, useRef } from 'react';

interface IntroVideoProps {
  onFinished: () => void;
}

const SOUND_URL_BASE64 = '/+MYxAAAAANIAUAAAAADN/ADOWAAAP/70NDgANACAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxDsAAANIAYAAABEUHAFf/70PCAAACAAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxHYAAANIAYAAABEUHAFf/70PCAAECAAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxCoAAANIAYAAABEUHAFf/70PCgAWCAAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxFYAAANIAYAAABEUHAFf/70PEgAYCAAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxHEAAANIAYAAABEUHAFf/70PEgAMCQAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxIgAAANIAYAAABEUHAFf/70PEgAWCQAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxJgAAANIAYAAABEUHAFf/70PEgAYCQAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxJwAAANIAYAAABEUHAFf/70PEgAYCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxKIAAANIAYAAABEUHAFf/70PEgAmCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxLgAAANIAYAAABEUHAFf/70PEgAmCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxMQAAANIAYAAABEUHAFf/70PEgAmCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxMgAAANIAYAAABEUHAFf/70PEgAYCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxMwAAANIAYAAABEUHAFf/70PEgAYCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxNIAAANIAYAAABEUHAFf/70PEgAWCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxNoAAANIAYAAABEUHAFf/70PEgAMCgAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxOAAAANIAYAAABEUHAFf/70PEgAMCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxPAAAANIAYAAABEUHAFf/70PFgAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxPgAAANIAYAAABEUHAFf/70PFgAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxQAAAANIAYAAABEUHAFf/70PFgAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxQgAAANIAYAAABEUHAFf/70PFgAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxQwAAANIAYAAABEUHAFf/70PFgAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxRAAAANIAYAAABEUHAFf/70PFgAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxRQAAANIAYAAABEUHAFf/70PFgAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxRwAAANIAYAAABEUHAFf/70PFgAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxSAAAANIAYAAABEUHAFf/70PFgAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxSQAAANIAYAAABEUHAFf/70PFgAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxSoAAANIAYAAABEUHAFf/70PFgAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxSgAAANIAYAAABEUHAFf/70PFgAMCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxTAAAANIAYAAABEUHAFf/70PFgAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxTQAAANIAYAAABEUHAFf/70PFgAMCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxTIAAANIAYAAABEUHAFf/70PFgAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxTwAAANIAYAAABEUHAFf/70PFgAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxUgAAANIAYAAABEUHAFf/70PFgAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxUwAAANIAYAAABEUHAFf/70PFgAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxVIAAAANIAYAAABEUHAFf/70PFgAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxVQAAANIAYAAABEUHAFf/70PFgAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxVwAAANIAYAAABEUHAFf/70PFgAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxWAAAANIAYAAABEUHAFf/70PFgAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxWQAAANIAYAAABEUHAFf/70PFgAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxWAAAANIAYAAABEUHAFf/70PFgAMCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxXIAAANIAYAAABEUHAFf/70PFwAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxXQAAANIAYAAABEUHAFf/70PFwAMCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxXgAAANIAYAAABEUHAFf/70PFwAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxYAAAANIAYAAABEUHAFf/70PFwAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxYgAAANIAYAAABEUHAFf/70PFwAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxYwAAANIAYAAABEUHAFf/70PFwAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxZAAAANIAYAAABEUHAFf/70PFwAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxZQAAANIAYAAABEUHAFf/70PFwAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxZgAAANIAYAAABEUHAFf/70PFwAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxZwAAANIAYAAABEUHAFf/70PFwAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxaAAAANIAYAAABEUHAFf/70PFwAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxaQAAANIAYAAABEUHAFf/70PFwAMCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxawAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxbQAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxbIAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxbwAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxcQAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxcgAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxcwAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxdAAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxdQAAANIAYAAABEUHAFf/70PGAAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxdwAAANIAYAAABEUHAFf/70PGAAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxeQAAANIAYAAABEUHAFf/70PGAAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxewAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxfQAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxfgAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxgAAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxggAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxgwAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxhAAAANIAYAAABEUHAFf/70PGAAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxhQAAANIAYAAABEUHAFf/70PGAAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxhwAAANIAYAAABEUHAFf/70PGAAmCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxiQAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxiwAAANIAYAAABEUHAFf/70PGAAYCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxjQAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxjgAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxkAAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxkQAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxkgAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxkwAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxlAAAANIAYAAABEUHAFf/70PGAAWCwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxlQAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxlwAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxmQAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxmwAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxnQAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxngAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxoAAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxoQAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxogAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxowAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxpAAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxpQAAANIAYAAABEUHAFf/70PGAAECwAADgAAAAAADEFNRTMuOTkuNVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxpwAAANIAYAAABEUHAFf/A4DAAAAAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxQUAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxQYAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxQoAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxQ4AAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxRIAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxRYAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxRcAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxRgAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxRoAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxRwAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxSAAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxSQAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxSYAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxSoAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxSwAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxTAAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxTEAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxTIAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8AAAAPAAAAAwAAAbB//+MYxTMAAAANIAYAAABEUHAFf/+vYwAAAAAAAAAAAAEluZm8==============';
const ANIMATION_DURATION = 3500;
const FADE_OUT_DURATION = 500;

// Web Audio API context - declared outside to be accessed by functions
let audioContext: AudioContext | null = null;
let audioBuffer: AudioBuffer | null = null;

// Function to decode base64 to ArrayBuffer
const base64ToArrayBuffer = (base64: string) => {
    const binaryString = window.atob(base64);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes.buffer;
};

// Pre-decode audio data when the component can
const prepareAudio = async () => {
    if (audioBuffer) return; // Already prepared
    try {
        audioContext = new (window.AudioContext || (window as any).webkitAudioContext)();
        const arrayBuffer = base64ToArrayBuffer(SOUND_URL_BASE64);
        audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
    } catch (e) {
        console.error("Failed to decode audio data:", e);
    }
};


const IntroVideo: React.FC<IntroVideoProps> = ({ onFinished }) => {
  const [hasStarted, setHasStarted] = useState(false);
  const [isFadingOut, setIsFadingOut] = useState(false);
  const audioSourceRef = useRef<AudioBufferSourceNode | null>(null);

  // Attempt to prepare audio as soon as possible
  useEffect(() => {
    prepareAudio();
  }, []);

  const handleStart = () => {
    setHasStarted(true);

    if (audioContext && audioBuffer) {
        // Resume context if it was suspended
        if (audioContext.state === 'suspended') {
            audioContext.resume();
        }

        // Create a new source node every time we play
        const source = audioContext.createBufferSource();
        source.buffer = audioBuffer;
        source.connect(audioContext.destination);
        source.start(0);
        audioSourceRef.current = source;
    } else {
        console.error("Audio context or buffer not ready for playback.");
    }
  };

  useEffect(() => {
    if (!hasStarted) return;

    const fadeTimer = setTimeout(() => {
      setIsFadingOut(true);
    }, ANIMATION_DURATION);

    const finishTimer = setTimeout(() => {
      onFinished();
    }, ANIMATION_DURATION + FADE_OUT_DURATION);

    return () => {
      clearTimeout(fadeTimer);
      clearTimeout(finishTimer);
      audioSourceRef.current?.stop(); // Stop audio if component unmounts
    };
  }, [hasStarted, onFinished]);

  if (!hasStarted) {
    return (
      <div className="fixed inset-0 z-50 bg-black flex flex-col items-center justify-center animate-fade-in">
        <div className="text-center p-4">
            <div className="flex items-center justify-center space-x-3 mb-4">
                <svg className="w-12 h-12 text-cyber-cyan" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                <h1 className="text-5xl md:text-6xl font-bold text-white" style={{textShadow: '0 0 15px rgba(8, 253, 216, 0.7)'}}>CareerCraft AI</h1>
            </div>
            <p className="text-gray-400 mt-2 mb-8 text-lg">Your AI-Powered Career Co-pilot</p>
            <button
                onClick={handleStart}
                className="bg-accent hover:bg-accent-hover text-white font-bold py-3 px-8 rounded-lg shadow-lg transition-transform transform hover:scale-105 animate-pulse-glow"
            >
                Begin
            </button>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className={`fixed inset-0 z-50 bg-black flex items-center justify-center transition-opacity duration-500 ${isFadingOut ? 'opacity-0' : 'opacity-100'}`}>
        <div className="netflix-logo-container">
          <h1 className="app-title">CareerCraft AI</h1>
        </div>
      </div>
      <style>{`
        .netflix-logo-container {
          position: relative;
          font-family: 'Bebas Neue', sans-serif;
          width: auto;
          padding: 0 2rem;
          height: 300px;
          display: flex;
          align-items: center;
          justify-content: center;
          overflow: hidden;
        }
        
        /* This pseudo element creates the initial line burst */
        .netflix-logo-container::before {
            content: '';
            position: absolute;
            left: 50%;
            top: 0;
            width: 4px;
            height: 100%;
            background-color: #E50914;
            transform-origin: center;
            animation: expand-line 0.4s ease-out forwards, flicker-effect 4s infinite;
             box-shadow: 
                -50px 0 10px #E50914, 50px 0 10px #E50914,
                -30px 0 10px #E50914, 30px 0 10px #E50914,
                -10px 0 10px #E50914, 10px 0 10px #E50914,
                0 0 25px #E50914;
        }

        @keyframes expand-line {
            from { transform: scaleY(0); }
            to { transform: scaleY(1); }
        }

        @keyframes flicker-effect {
          0%, 18%, 22%, 25%, 53%, 57%, 100% {
              opacity: 0.99;
          }
          20%, 24%, 55% {
              opacity: 0.8;
          }
        }

        .app-title {
          font-weight: bold;
          font-size: 6rem;
          color: #E50914;
          line-height: 1;
          position: relative;
          transform-origin: center;
          animation: title-grow 3.2s ease-out 0.3s forwards;
          opacity: 0;
          text-shadow: 0 0 15px rgba(0,0,0,0.7);
        }

        @keyframes title-grow {
            0% {
                opacity: 0;
                transform: scale(0.7);
            }
            20% {
                opacity: 1;
                transform: scale(1.1);
            }
            40% {
                transform: scale(1);
                text-shadow: 0 0 15px rgba(0,0,0,0.7), 0 0 25px #b1060e;
            }
            100% {
                opacity: 1;
                transform: scale(1);
            }
        }
      `}</style>
    </>
  );
};

export default IntroVideo;